INSERT INTO NOTICE(HIT) VALUES(1);
INSERT INTO NOTICE(HIT) VALUES(12);
INSERT INTO NOTICE(HIT) VALUES(9);

SELECT HIT+1 HIT FROM NOTICE;

SELECT * FROM MEMBER;

INSERT INTO MEMBER(ID, PWD, NAME) VALUES('sorrel', '123', '¼ÒÀ²');

DELETE FROM MEMBER WHERE ID='sorrel';

SELECT HIT+1 HIT FROM NOTICE;

SELECT NAME||'('||ID||')' NAME FROM MEMBER;
