
CREATE TABLE MEMBER
(
    ID VARCHAR2(50),
    PWD VARCHAR2(50),
    NAME VARCHAR2(50),
    GENDER VARCHAR2(50),
    AGE NUMBER,
    BIRTHDAY VARCHAR2(50),
    PHONE VARCHAR2(50),
    REGDATE DATE    
);

CREATE TABLE "COMMENT"
(
     ID		NUMBER,
     CONTENT	NVARCHAR2(2000),
     REGDATE  	TIMESTAMP,
     WRITER_ID	NVARCHAR2(50),
     NOTICE_ID	NUMBER
);

CREATE TABLE NOTICE
(
    ID          NUMBER,
    TITLE       NVARCHAR2(100),
    WRITER_ID   NVARCHAR2(50),
    CONTENT     CLOB,
    REGDATE     TIMESTAMP,
    HIT         NUMBER,
    FILES       NVARCHAR2(1000)
);

CREATE TABLE ROLE
(
    ID          VARCHAR(50),
    DESCRIPTION VARCHAR2(500)
);

CREATE TABLE MEMBER_ROLE
(
    MEMBER_ID   NVARCHAR2(50),
    ROLE_ID     VARCHAR(50)
);

INSERT INTO NOTICE(HIT) VALUES(1);
INSERT INTO NOTICE(HIT) VALUES(12);
INSERT INTO NOTICE(HIT) VALUES(9);

SELECT HIT+1 HIT FROM NOTICE;

SELECT * FROM MEMBER;

INSERT INTO MEMBER(ID, PWD, NAME) VALUES('sorrel', '123', '수영');

DELETE FROM MEMBER WHERE ID='sorrel';

SELECT HIT+1 HIT FROM NOTICE;

SELECT NAME||'('||ID||')' NAME FROM MEMBER;
