SELECT * FROM MEMBER;

SELECT RPAD(NAME, 6, '_') NAME FROM MEMBER;

SELECT INSTR('ALL WE NEED TO IS JUST TO...', 'TO') FROM DUAL; 

SELECT INSTR('ALL WE NEED TO IS JUST TO...', 'TO', 15) FROM DUAL; 

SELECT INSTR('ALL WE NEED TO IS JUST TO...', 'TO', 1, 2) FROM DUAL; 

SELECT INSTR(PHONE, '-', 1, 2) PHONE FROM MEMBER;

SELECT INSTR(PHONE, '-', 1, 2) - INSTR (PHONE, '-', 1, 1) - 1 PHONE FROM MEMBER;

SELECT LENGTH('WHERE WE ARE') FROM DUAL;

SELECT PHONE FROM MEMBER;

SELECT LENGTH(REPLACE(PHONE, '-', ''))PHONE FROM MEMBER;

SELECT ASCII('A') FROM DUAL;

SELECT CHR(122) FROM DUAL; 

COMMIT;