SELECT SYSDATE, CURRENT_DATE FROM DUAL;

ALTER SESSION SET NLS_DATE_FORMAT = 'YYYY-MM-DD HH24:MI:SS';
ALTER SESSION SET TIME_ZONE = '09:00'; 

SELECT EXTRACT(YEAR FROM SYSDATE) FROM DUAL;

SELECT EXTRACT(DAY FROM SYSDATE) FROM DUAL;

SELECT EXTRACT(MONTH FROM SYSDATE)||'월' FROM DUAL;

SELECT * FROM MEMBER WHERE EXTRACT (MONTH FROM REGDATE) IN(2,3,11,12);

SELECT * FROM MEMBER;

UPDATE MEMBER SET REGDATE = '2023-02-09' WHERE ID='sorrel';
UPDATE MEMBER SET REGDATE = '2022-07-11' WHERE ID='hanee';
UPDATE MEMBER SET REGDATE = '2023-01-01' WHERE ID='jiyou';
UPDATE MEMBER SET REGDATE = '2022-11-17' WHERE ID='youl';
UPDATE MEMBER SET REGDATE = '2022-12-27' WHERE ID='yeon';

SELECT ADD_MONTHS(SYSDATE, 1) FROM DUAL;

SELECT ADD_MONTHS(SYSDATE, -1) FROM DUAL;

SELECT * FROM MEMBER WHERE ADD_MONTHS(SYSDATE, -6) < REGDATE;

SELECT MONTHS_BETWEEN(SYSDATE, TO_DATE('2022-11-25')) FROM DUAL;

SELECT NEXT_DAY(SYSDATE, '�����') FROM DUAL;

SELECT LAST_DAY(SYSDATE) FROM DUAL;

SELECT LAST_DAY(ADD_MONTHS(SYSDATE, 1)) FROM DUAL;

--세기
SELECT ROUND(SYSDATE, 'CC') FROM DUAL;

SELECT ROUND(SYSDATE, 'YEAR') FROM DUAL;

--분기
SELECT ROUND(SYSDATE, 'Q') FROM DUAL;

SELECT ROUND(SYSDATE, 'MONTH') FROM DUAL;

SELECT ROUND(SYSDATE, 'W') FROM DUAL;

SELECT ROUND(SYSDATE, 'DAY') FROM DUAL;

SELECT ROUND(SYSDATE, 'D') FROM DUAL;

SELECT ROUND(SYSDATE, 'HH') FROM DUAL;

SELECT ROUND(SYSDATE, 'MI') FROM DUAL;



SELECT TRUNC(SYSDATE, 'CC') FROM DUAL; 

SELECT TRUNC(SYSDATE, 'YEAR') FROM DUAL;

COMMIT;