SELECT * FROM DICT;

SELECT * FROM USER_TABLES;

SELECT * FROM USER_TAB_COLUMNS WHERE TABLE_NAME = 'MEMBER';

INSERT INTO MEMBER(ID, PWD, NAME, GENDER, PHONE)
VALUES('sorrel2', '123', '수지' , '여', '01012345678');

COMMIT;

ALTER TABLE MEMBER
ADD CONSTRAINT MEMBER_PHONE_CHK1 CHECK(REGEXP_LIKE(PHONE,'01\d-\d{3,4}-\d{4}'));

SELECT NOTICE_ID_SEQ.NEXTVAL FROM DUAL;