SELECT TO_CHAR(123) || 'HELLO' FROM DUAL;

SELECT TO_CHAR(12345678.34567, '099,999,999.99') || 'HELLO' FROM DUAL;

SELECT TO_CHAR(SYSDATE,'YYYY-MM-DD HH24:MI:SS') FROM DUAL;

SELECT TO_CHAR(SYSDATE,'YY-MM-DD HH24:MI:SS') FROM DUAL;

SELECT TO_DATE('2023-02-19') FROM DUAL;

SELECT TO_DATE('2023-02-19 11:04:50', 'YYYY-MM-DD HH24:MI:SS') FROM DUAL;

SELECT TO_TIMESTAMP('2023-02-19 23:04:50', 'YYYY-MM-DD HH24:MI:SS') FROM DUAL;

SELECT TO_NUMBER('1994') FROM DUAL;

SELECT TO_NUMBER('2') + 3 FROM DUAL;

SELECT * FROM MEMBER;

SELECT NVL(EMAIL, '없음') FROM MEMBER;

SELECT NVL2(EMAIL,'있음', '없음') FROM MEMBER;

SELECT NAME, NULLIF(AGE, 26) FROM MEMBER;

SELECT PHONE FROM MEMBER;

SELECT DECODE(SUBSTR(PHONE,1,3)
                            , '011','SK'
                            , '016', 'KT'
                            , '자유') FROM MEMBER;

SELECT * FROM MEMBER ORDER BY NAME DESC;

SELECT * FROM MEMBER WHERE NAME LIKE '박%' ORDER BY AGE;

SELECT * FROM MEMBER WHERE NAME LIKE '박%' ORDER BY AGE, NAME;

SELECT SUM(AGE) FROM MEMBER;

SELECT AVG(AGE) FROM MEMBER;

SELECT COUNT(AGE) FROM MEMBER;

SELECT MIN(AGE) FROM MEMBER;

SELECT MAX(AGE) FROM MEMBER;

SELECT ID, COUNT(AGE) FROM MEMBER GROUP BY ID;

SELECT * FROM NOTICE;

UPDATE NOTICE SET WRITER_ID='sorrel' WHERE WRITER_ID='eng';

SELECT WRITER_ID, COUNT(ID) COUNT FROM NOTICE  GROUP BY WRITER_ID ORDER BY COUNT(ID) DESC;

SELECT WRITER_ID, COUNT(ID) COUNT FROM NOTICE  GROUP BY WRITER_ID HAVING COUNT(ID) < 2;

SELECT ROW_NUMBER() OVER (ORDER BY AGE) , ID, NAME, BIRTHDAY, PHONE, REGDATE, AGE 
FROM MEMBER;

SELECT RANK() OVER (ORDER BY AGE) , ID, NAME, BIRTHDAY, PHONE, REGDATE, AGE 
FROM MEMBER;

SELECT DENSE_RANK() OVER (ORDER BY AGE) , ID, NAME, BIRTHDAY, PHONE, REGDATE, AGE 
FROM MEMBER;

UPDATE NOTICE SET HIT=23 WHERE WRITER_ID = 'quest';

UPDATE NOTICE SET HIT=23 WHERE WRITER_ID = 'hanee';

UPDATE NOTICE SET HIT=12 WHERE WRITER_ID = 'OKAY';

UPDATE NOTICE SET HIT=5 WHERE WRITER_ID = 'jiyou';

UPDATE NOTICE SET HIT=9 WHERE TITLE = 'JDBC란 무엇인가?';

UPDATE NOTICE SET HIT=2 WHERE TITLE = '효율적으로 영어 공부하기';

SELECT * FROM MEMBER;

SELECT DENSE_RANK() OVER (ORDER BY HIT DESC) , WRITER_ID, TITLE, CONTENT, HIT
FROM NOTICE;

SELECT DENSE_RANK() OVER (PARTITION BY WRITER_ID ORDER BY HIT DESC) , WRITER_ID, TITLE, CONTENT, HIT
FROM NOTICE;

SELECT * FROM (SELECT * FROM MEMBER ORDER BY REGDATE DESC) WHERE ROWNUM BETWEEN 1 AND 3;

SELECT * FROM MEMBER WHERE AGE >= (SELECT AVG(AGE) FROM MEMBER);

COMMIT;

